AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - 'bin/*'
    - 'config/*'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/Lambda:
  EnforcedStyle: literal

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*.rb'
